In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv(r'Countries.csv')

In [6]:
df.shape

(194, 64)

In [7]:
df.info

<bound method DataFrame.info of                 country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]>

In [8]:
df.describe

<bound method NDFrame.describe of                 country                             country_long  \
0           Afghanistan             Islamic State of Afghanistan
1               Albania                      Republic of Albania
2               Algeria  People's Democratic Republic of Algeria
3               Andorra                  Principality of Andorra
4                Angola              People's Republic of Angola
..                  ...                                      ...
189             Vietnam            Socialist Republic of Vietnam
190  West Bank and Gaza                       West Bank and Gaza
191               Yemen                        Republic of Yemen
192              Zambia                       Republic of Zambia
193            Zimbabwe                     Republic of Zimbabwe

               currency      capital_city              region continent  \
0        Afghan afghani             Kabul       Southern Asia      Asia
1          Albanian lek            Tirana     Southern Europe    Europe
2        Algerian dinar           Algiers     Northern Africa    Africa
3                  Euro  Andorra la Vella     Southern Europe    Europe
4        Angolan kwanza            Luanda       Middle Africa    Africa
..                  ...               ...                 ...       ...
189     Vietnamese dong             Hanoi  South-Eastern Asia      Asia
190  Israeli new shekel          Ramallah        Western Asia      Asia
191         Yemeni rial            Sana'a        Western Asia      Asia
192  New Zambian kwacha            Lusaka      Eastern Africa    Africa
193         U.S. dollar            Harare      Eastern Africa    Africa

         demonym   latitude   longitude  agricultural_land  ...  population  \
0         Afghan  33.000000   65.000000           383560.0  ...    41128771
1       Albanian  41.000000   20.000000            11655.5  ...     2775634
2       Algerian  28.000000    3.000000           413588.0  ...    44903225
3       Andorran  42.500000    1.500000              187.2  ...       79824
4        Angolan -12.500000   18.500000           569525.0  ...    35588987
..           ...        ...         ...                ...  ...         ...
189   Vietnamese  16.166667  107.833333           123600.0  ...    98186856
190  Palestinian  31.900000   35.200000             4449.0  ...     5043612
191       Yemeni  15.000000   48.000000           234520.0  ...    33696614
192      Zambian -15.000000   30.000000           238360.0  ...    20017675
193   Zimbabwean -20.000000   30.000000           162000.0  ...    16320537

     women_parliament_seats_pct  rural_population  urban_population  press  \
0                      27.01610          30181937          10946834   2.14
1                      35.71430           1004807           1770827   2.62
2                       8.10811          11328186          33575039   1.71
3                      46.42860              9730             70094   3.17
4                      33.63640          11359649          24229338   2.24
..                          ...               ...               ...    ...
189                    30.26050          60123739          38063117   1.04
190                         NaN           1145354           3898258   1.75
191                     0.00000          20491585          13205029   1.27
192                    15.06020          10857387           9160288   2.15
193                    30.56600          11033499           5287038   1.85

     democracy_score  democracy_type  median_age       political_leader  \
0               2.97   Authoritarian        12.9           Ashraf Ghani
1               5.98   Hybrid regime        33.7               Edi Rama
2               3.50   Authoritarian        24.0   Abdelmadjid Tebboune
3               0.00         Unknown        38.9    Xavier Espot Zamora
4               3.62   Authoritarian        12.4          João Lourenço
..               ...             ...         ...                    ...
189             3.08   Authoritarian        28.4       Nguyễn Phú Trọng
190             4.39   Hybrid regime        15.4                    NaN
191             1.95   Authoritarian        14.8  Abdrabbuh Mansur Hadi
192             5.61   Hybrid regime        13.2            Edgar Lungu
193             3.16   Authoritarian        14.2     Emmerson Mnangagwa

                                        title
0                                   President
1                              Prime Minister
2                                   President
3                          Head of Government
4                                   President
..                                        ...
189  General Secretary of the Communist Party
190                                       NaN
191                                 President
192                                 President
193                                 President

[194 rows x 64 columns]>

In [9]:
df[df['population'] == df['population'].max()]["country"]

75    India
Name: country, dtype: object

In [10]:
df.loc[df["population"].idxmax(), "capital_city"]

'New Delhi'

In [11]:
df[df["population"] == df["population"].min()]["country"]

179    Tuvalu
Name: country, dtype: object

In [12]:
df[df["population"] == df["population"].min()]["capital_city"]

179    Funafuti
Name: capital_city, dtype: object

In [13]:
df.nlargest(5, "democracy_score")[["country", "democracy_score"]]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [14]:
df.nlargest(5, "population")[["country", "population"]]

           country  population
75           India  1417173173
34           China  1412175000
184  United States   333287557
76       Indonesia   275501339
129       Pakistan   235824862

In [15]:
df.nsmallest(5, "population")[["country", "population"]]

        country  population
179      Tuvalu       11312
119       Nauru       12668
130       Palau       18055
143  San Marino       33660
112      Monaco       36469

In [16]:
df.loc[df["democracy_score"].idxmax(), "country"]

'Norway'

In [17]:
df.loc[df["democracy_score"].idxmin(), "country"]

'Andorra'

In [18]:
df.sort_values(by="democracy_score", ascending=False, inplace=True)

In [19]:
df["region"].unique()

array(['Northern Europe', 'Australia and New Zealand', 'Northern America',
       'Western Europe', 'South America', 'Eastern Africa',
       'Southern Europe', 'Central America', 'Eastern Asia',
       'Western Africa', 'Southern Africa', 'Western Asia',
       'Eastern Europe', 'Southern Asia', 'South-Eastern Asia',
       'Caribbean', 'Northern Africa', 'Melanesia', 'Central Asia',
       'Middle Africa', 'Micronesia', 'Polynesia'], dtype=object)

In [20]:
df[df["region"] == "Eastern Europe"].shape[0]

10

In [21]:
df.nlargest(2, "population").iloc[1]["political_leader"]

'Xi Jinping'

In [22]:
df.nlargest(2, "population").iloc[1]["country"]

'China'

In [23]:
df.nlargest(2, "population").iloc[1]["capital_city"]

'Beijing'

In [24]:
df[df["region"] == "Eastern Europe"].shape[0]

10

In [25]:
df.nlargest(2, "population").iloc[1]["political_leader"]

'Xi Jinping'

In [26]:
df[df["region"] == "Asia"].nlargest(1, "population")["country"]

Series([], Name: country, dtype: object)

In [27]:
df[df["region"] == "Europe"].nsmallest(1, "population")["country"]

Series([], Name: country, dtype: object)

In [28]:
df.groupby("region")["population"].mean()

region
Australia and New Zealand    1.555152e+07
Caribbean                    3.053804e+06
Central America              2.232179e+07
Central Asia                 1.569139e+07
Eastern Africa               2.710280e+07
Eastern Asia                 3.236792e+08
Eastern Europe               2.819816e+07
Melanesia                    3.030850e+06
Micronesia                   6.353760e+04
Middle Africa                2.069911e+07
Northern Africa              4.323233e+07
Northern America             1.861087e+08
Northern Europe              1.059054e+07
Polynesia                    1.135173e+05
South America                3.643607e+07
South-Eastern Asia           6.188967e+07
Southern Africa              1.371974e+07
Southern Asia                2.230998e+08
Southern Europe              1.004744e+07
Western Africa               2.681747e+07
Western Asia                 1.720938e+07
Western Europe               2.221409e+07
Name: population, dtype: float64