In [3]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r'dataset_100_entries.csv')

In [8]:
df.head()

   id     name  age    city  score
0   1  Person1   18  London     70
1   2  Person2   19   Paris     71
2   3  Person3   20   Tokyo     72
3   4  Person4   21  Berlin     73
4   5  Person5   22  Sydney     74

In [15]:
df.loc[4, "name"]

'Person5'

In [19]:
df.loc[4:9, ["name", "age"]]

       name  age
4   Person5   22
5   Person6   23
6   Person7   24
7   Person8   25
8   Person9   26
9  Person10   27

In [20]:
df.replace("Male", "M")

     id       name  age     city  score
0     1    Person1   18   London     70
1     2    Person2   19    Paris     71
2     3    Person3   20    Tokyo     72
3     4    Person4   21   Berlin     73
4     5    Person5   22   Sydney     74
..  ...        ...  ...      ...    ...
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

[100 rows x 5 columns]

In [21]:
df.replace({
    "Male": "M",
    "Female": "F"
})

     id       name  age     city  score
0     1    Person1   18   London     70
1     2    Person2   19    Paris     71
2     3    Person3   20    Tokyo     72
3     4    Person4   21   Berlin     73
4     5    Person5   22   Sydney     74
..  ...        ...  ...      ...    ...
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

[100 rows x 5 columns]

In [25]:
df.tail()

     id       name  age     city  score
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

In [24]:
df.sample(5)

    id      name  age    city  score
71  72  Person72   29   Paris     81
46  47  Person47   24    Rome     86
9   10  Person10   27  Mumbai     79
66  67  Person67   24    Rome     76
30  31  Person31   28  London     70

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int64
 1   name    100 non-null    object
 2   age     100 non-null    int64
 3   city    100 non-null    object
 4   score   100 non-null    int64
dtypes: int64(3), object(2)
memory usage: 4.0+ KB

In [27]:
df.describe()

               id         age       score
count  100.000000  100.000000  100.000000
mean    50.500000   27.500000   83.500000
std     29.011492    5.795331    8.833476
min      1.000000   18.000000   70.000000
25%     25.750000   22.750000   76.000000
50%     50.500000   27.500000   83.000000
75%     75.250000   32.250000   91.000000
max    100.000000   37.000000   99.000000

In [28]:
df.shape

(100, 5)

In [29]:
df.columns

Index(['id', 'name', 'age', 'city', 'score'], dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [31]:
df.iloc[10:20]

    id      name  age     city  score
10  11  Person11   28   London     80
11  12  Person12   29    Paris     81
12  13  Person13   30    Tokyo     82
13  14  Person14   31   Berlin     83
14  15  Person15   32   Sydney     84
15  16  Person16   33  Toronto     85
16  17  Person17   34     Rome     86
17  18  Person18   35    Dubai     87
18  19  Person19   36    Seoul     88
19  20  Person20   37   Mumbai     89

In [32]:
df[df["age"] > 25]

     id       name  age     city  score
8     9    Person9   26    Seoul     78
9    10   Person10   27   Mumbai     79
10   11   Person11   28   London     80
11   12   Person12   29    Paris     81
12   13   Person13   30    Tokyo     82
13   14   Person14   31   Berlin     83
14   15   Person15   32   Sydney     84
15   16   Person16   33  Toronto     85
16   17   Person17   34     Rome     86
17   18   Person18   35    Dubai     87
18   19   Person19   36    Seoul     88
19   20   Person20   37   Mumbai     89
28   29   Person29   26    Seoul     98
29   30   Person30   27   Mumbai     99
30   31   Person31   28   London     70
31   32   Person32   29    Paris     71
32   33   Person33   30    Tokyo     72
33   34   Person34   31   Berlin     73
34   35   Person35   32   Sydney     74
35   36   Person36   33  Toronto     75
36   37   Person37   34     Rome     76
37   38   Person38   35    Dubai     77
38   39   Person39   36    Seoul     78
39   40   Person40   37   Mumbai     79
48   49   Person49   26    Seoul     88
49   50   Person50   27   Mumbai     89
50   51   Person51   28   London     90
51   52   Person52   29    Paris     91
52   53   Person53   30    Tokyo     92
53   54   Person54   31   Berlin     93
54   55   Person55   32   Sydney     94
55   56   Person56   33  Toronto     95
56   57   Person57   34     Rome     96
57   58   Person58   35    Dubai     97
58   59   Person59   36    Seoul     98
59   60   Person60   37   Mumbai     99
68   69   Person69   26    Seoul     78
69   70   Person70   27   Mumbai     79
70   71   Person71   28   London     80
71   72   Person72   29    Paris     81
72   73   Person73   30    Tokyo     82
73   74   Person74   31   Berlin     83
74   75   Person75   32   Sydney     84
75   76   Person76   33  Toronto     85
76   77   Person77   34     Rome     86
77   78   Person78   35    Dubai     87
78   79   Person79   36    Seoul     88
79   80   Person80   37   Mumbai     89
88   89   Person89   26    Seoul     98
89   90   Person90   27   Mumbai     99
90   91   Person91   28   London     70
91   92   Person92   29    Paris     71
92   93   Person93   30    Tokyo     72
93   94   Person94   31   Berlin     73
94   95   Person95   32   Sydney     74
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

In [33]:
df[(df["city"] == "London") | (df["city"] == "Paris")]

    id      name  age    city  score
0    1   Person1   18  London     70
1    2   Person2   19   Paris     71
10  11  Person11   28  London     80
11  12  Person12   29   Paris     81
20  21  Person21   18  London     90
21  22  Person22   19   Paris     91
30  31  Person31   28  London     70
31  32  Person32   29   Paris     71
40  41  Person41   18  London     80
41  42  Person42   19   Paris     81
50  51  Person51   28  London     90
51  52  Person52   29   Paris     91
60  61  Person61   18  London     70
61  62  Person62   19   Paris     71
70  71  Person71   28  London     80
71  72  Person72   29   Paris     81
80  81  Person81   18  London     90
81  82  Person82   19   Paris     91
90  91  Person91   28  London     70
91  92  Person92   29   Paris     71

In [34]:
df.sort_values("age")

     id       name  age    city  score
0     1    Person1   18  London     70
80   81   Person81   18  London     90
20   21   Person21   18  London     90
60   61   Person61   18  London     70
40   41   Person41   18  London     80
..  ...        ...  ...     ...    ...
79   80   Person80   37  Mumbai     89
39   40   Person40   37  Mumbai     79
19   20   Person20   37  Mumbai     89
59   60   Person60   37  Mumbai     99
99  100  Person100   37  Mumbai     79

[100 rows x 5 columns]

In [35]:
df.sort_values("score", ascending=False)

    id      name  age    city  score
89  90  Person90   27  Mumbai     99
29  30  Person30   27  Mumbai     99
59  60  Person60   37  Mumbai     99
88  89  Person89   26   Seoul     98
28  29  Person29   26   Seoul     98
..  ..       ...  ...     ...    ...
61  62  Person62   19   Paris     71
30  31  Person31   28  London     70
90  91  Person91   28  London     70
60  61  Person61   18  London     70
0    1   Person1   18  London     70

[100 rows x 5 columns]

In [36]:
df.isnull()

       id   name    age   city  score
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False  False  False
3   False  False  False  False  False
4   False  False  False  False  False
..    ...    ...    ...    ...    ...
95  False  False  False  False  False
96  False  False  False  False  False
97  False  False  False  False  False
98  False  False  False  False  False
99  False  False  False  False  False

[100 rows x 5 columns]

In [37]:

df.isnull().sum()

id       0
name     0
age      0
city     0
score    0
dtype: int64

In [38]:
df.dropna()

     id       name  age     city  score
0     1    Person1   18   London     70
1     2    Person2   19    Paris     71
2     3    Person3   20    Tokyo     72
3     4    Person4   21   Berlin     73
4     5    Person5   22   Sydney     74
..  ...        ...  ...      ...    ...
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

[100 rows x 5 columns]

In [39]:

df.fillna(0)

     id       name  age     city  score
0     1    Person1   18   London     70
1     2    Person2   19    Paris     71
2     3    Person3   20    Tokyo     72
3     4    Person4   21   Berlin     73
4     5    Person5   22   Sydney     74
..  ...        ...  ...      ...    ...
95   96   Person96   33  Toronto     75
96   97   Person97   34     Rome     76
97   98   Person98   35    Dubai     77
98   99   Person99   36    Seoul     78
99  100  Person100   37   Mumbai     79

[100 rows x 5 columns]