In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Akshat", "Rahul", "Priya", "Rohan", "Neha"],
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Salary": [50000, 60000, 45000, 40000, 55000]
})

print(df)

     Name Department  Salary
0  Akshat         IT   50000
1   Rahul         IT   60000
2   Priya         HR   45000
3   Rohan         HR   40000
4    Neha         IT   55000

In [3]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)

print(pivot)

             Salary
Department
HR          42500.0
IT          55000.0

In [4]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="sum"
)

print(pivot)

            Salary
Department
HR           85000
IT          165000

In [5]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="count"
)

print(pivot)

            Salary
Department
HR               2
IT               3

In [6]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Gender": ["M", "F", "F", "M", "M"],
    "Salary": [50000, 60000, 45000, 40000, 55000]
})

pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

print(pivot)

Gender            F        M
Department
HR          45000.0  40000.0
IT          60000.0  52500.0

In [7]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean", "sum", "max", "min"]
)

print(pivot)

               mean     sum    max    min
             Salary  Salary Salary Salary
Department
HR          42500.0   85000  45000  40000
IT          55000.0  165000  60000  50000

In [8]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 45000, 40000],
    "Bonus": [5000, 6000, 3000, 3500]
})

pivot = pd.pivot_table(
    df,
    values=["Salary", "Bonus"],
    index="Department",
    aggfunc="sum"
)

print(pivot)

            Bonus  Salary
Department
HR           6500   85000
IT          11000  110000

In [9]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean",
    fill_value=0
)

KeyError: 'Gender'

In [10]:
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="sum",
    margins=True
)

print(pivot)

            Salary
Department
HR           85000
IT          110000
All         195000

In [11]:
df = pd.DataFrame({
    "Name": ["Akshat", "Rahul"],
    "Subject": ["Math", "Science"],
    "Marks": [90, 95]
})

df.pivot(index="Name", columns="Subject", values="Marks")

Subject  Math  Science
Name
Akshat   90.0      NaN
Rahul     NaN     95.0

In [12]:
df = pd.DataFrame({
    "Name": ["Akshat", "Akshat"],
    "Subject": ["Math", "Math"],
    "Marks": [90, 95]
})

pd.pivot_table(
    df,
    values="Marks",
    index="Name",
    columns="Subject",
    aggfunc="mean"
)

Subject  Math
Name
Akshat   92.5

In [13]:
# Arithmetic Operations
# Example DataFrame
import pandas as pd

df = pd.DataFrame({
    "A": [10, 20, 30],
    "B": [5, 10, 15]
})

print(df)

    A   B
0  10   5
1  20  10
2  30  15

In [14]:
df["A"] + df["B"]

0    15
1    30
2    45
dtype: int64

In [15]:
df["A"] - df["B"]

0     5
1    10
2    15
dtype: int64

In [16]:
df["A"] * df["B"]

0     50
1    200
2    450
dtype: int64

In [17]:
df["A"] / df["B"]

0    2.0
1    2.0
2    2.0
dtype: float64

In [19]:
# Comparison Operations
df["A"] > 15

0    False
1     True
2     True
Name: A, dtype: bool

In [20]:
df["A"] == 20

0    False
1     True
2    False
Name: A, dtype: bool

In [21]:
# Logical Operations
# AND (&)
df[(df["A"] > 10) & (df["B"] > 5)]

    A   B
1  20  10
2  30  15

In [22]:
# OR (|)
df[(df["A"] > 20) | (df["B"] == 5)]

    A   B
0  10   5
2  30  15

In [24]:
# NOT (~)
df[~(df["A"] > 20)]

    A   B
0  10   5
1  20  10

In [25]:
# Mathematical Operations
# Sum
df["A"].sum()

np.int64(60)

In [26]:
# Mean
df["A"].mean()

np.float64(20.0)

In [ ]:
# Maximum
df["A"].max()

In [27]:
# Minimum
df["A"].min()

10

In [28]:
# Count
df["A"].count()

np.int64(3)

In [29]:
# Standard Deviation
df["A"].std()

10.0

In [30]:
# String Operations
df = pd.DataFrame({
    "Name": ["akshat", "rahul", "priya"]
})
# Upper Case
df["Name"].str.upper()

0    AKSHAT
1     RAHUL
2     PRIYA
Name: Name, dtype: object

In [31]:
# Lower Case
df["Name"].str.lower()
# Title Case
df["Name"].str.title()

0    Akshat
1     Rahul
2     Priya
Name: Name, dtype: object

In [32]:
# Contains
df["Name"].str.contains("a")
# Replace
df["Name"].str.replace("a", "@")

0    @ksh@t
1     r@hul
2     priy@
Name: Name, dtype: object

In [33]:
# Apply Operation
df = pd.DataFrame({
    "Marks": [70, 80, 90]
})

df["Marks"] = df["Marks"].apply(lambda x: x + 5)

In [34]:
# Map Operation
df = pd.DataFrame({
    "Gender": ["M", "F", "M"]
})

mapping = {
    "M": "Male",
    "F": "Female"
}

df["Gender"] = df["Gender"].map(mapping)

In [ ]:
# 9. Sorting
# Ascending
df.sort_values("Marks")

In [35]:
# Value Counts
df["Gender"].value_counts()

Gender
Male      2
Female    1
Name: count, dtype: int64

In [36]:
# Unique Values
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [37]:
# Number of Unique Values
df["Gender"].nunique()

2

In [39]:
# GroupBy Operation
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 40000, 45000]
})

df.groupby("Department")["Salary"].sum()

Department
HR     85000
IT    110000
Name: Salary, dtype: int64

In [40]:
# Cumulative Operations
# Cumulative Sum
df["Salary"].cumsum()

0     50000
1    110000
2    150000
3    195000
Name: Salary, dtype: int64

In [41]:
# Ranking
df["Salary"].rank()

0    3.0
1    4.0
2    1.0
3    2.0
Name: Salary, dtype: float64

In [42]:
# 17. Percentage Change
df["Salary"].pct_change()

0         NaN
1    0.200000
2   -0.333333
3    0.125000
Name: Salary, dtype: float64

In [43]:
# 18. Correlation
df.corr(numeric_only=True)

        Salary
Salary     1.0

In [44]:
# 19. Describe
df.describe()

             Salary
count      4.000000
mean   48750.000000
std     8539.125638
min    40000.000000
25%    43750.000000
50%    47500.000000
75%    52500.000000
max    60000.000000

In [45]:
# Finding Data in Pandas (Selection & Filtering)

# Finding data means selecting specific rows, columns, or values from a DataFrame.

# Sample DataFrame
import pandas as pd

df = pd.DataFrame({
    "ID": [101, 102, 103, 104],
    "Name": ["Akshat", "Rahul", "Priya", "Rohan"],
    "Age": [21, 22, 20, 23],
    "Marks": [90, 85, 95, 80]
})

print(df)

    ID    Name  Age  Marks
0  101  Akshat   21     90
1  102   Rahul   22     85
2  103   Priya   20     95
3  104   Rohan   23     80

In [46]:
# Find a Column
df["Name"]

0    Akshat
1     Rahul
2     Priya
3     Rohan
Name: Name, dtype: object

In [47]:
# Find a Row using loc[]
# loc[] uses row labels (index names).
df.loc[2]

ID         103
Name     Priya
Age         20
Marks       95
Name: 2, dtype: object

In [48]:
# Find a Row using iloc[]

# iloc[] uses row positions.

df.iloc[1]

ID         102
Name     Rahul
Age         22
Marks       85
Name: 1, dtype: object

In [49]:
# Find a Specific Value
df.loc[0, "Name"]

'Akshat'

In [50]:
# Find Rows by Condition

# Age greater than 21

df[df["Age"] > 21]

    ID   Name  Age  Marks
1  102  Rahul   22     85
3  104  Rohan   23     80

In [51]:
# Find Data Using String Functions

# Names containing "a"

df[df["Name"].str.contains("a", case=False)]

    ID    Name  Age  Marks
0  101  Akshat   21     90
1  102   Rahul   22     85
2  103   Priya   20     95
3  104   Rohan   23     80

In [52]:
# 19. Find Largest Values

# Top 2 highest marks

df.nlargest(2, "Marks")

    ID    Name  Age  Marks
2  103   Priya   20     95
0  101  Akshat   21     90

In [53]:
# Find Smallest Values
df.nsmallest(2, "Marks")

    ID   Name  Age  Marks
3  104  Rohan   23     80
1  102  Rahul   22     85