In [ ]:
import pandas as pd

In [2]:
# Concatenation (pd.concat())
# Used to join DataFrames vertically or horizontally.
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Akshat", "Rahul"],
    "Age": [21, 22]
})

df2 = pd.DataFrame({
    "Name": ["Priya", "Rohan"],
    "Age": [20, 23]
})

result = pd.concat([df1, df2])

print(result)

     Name  Age
0  Akshat   21
1   Rahul   22
0   Priya   20
1   Rohan   23

In [5]:
df1 = pd.DataFrame({
    "Name": ["Akshat", "Rahul"]
})

df2 = pd.DataFrame({
    "Age": [21, 22]
})

result = pd.concat([df1, df2], axis=1)

print(result)

     Name  Age
0  Akshat   21
1   Rahul   22

In [6]:
df1 = pd.DataFrame({
    "Name": ["Akshat", "Rahul"]
})

df2 = pd.DataFrame({
    "Age": [21, 22]
})

pd.concat([df1, df2])

     Name   Age
0  Akshat   NaN
1   Rahul   NaN
0     NaN  21.0
1     NaN  22.0

In [10]:
# Merge (pd.merge())
students = pd.DataFrame({
    "ID":[1,2,3],
    "Name":["Akshat","Rahul","Priya"]
})

In [11]:
marks = pd.DataFrame({
    "ID":[1,2,4],
    "Marks":[95,88,75]
})

In [12]:
# Inner Merge
pd.merge(students, marks, on="ID")

   ID    Name  Marks
0   1  Akshat     95
1   2   Rahul     88

In [14]:
# Left Merge
# All rows from left dataframe.
pd.merge(students, marks, on="ID", how="left")

   ID    Name  Marks
0   1  Akshat   95.0
1   2   Rahul   88.0
2   3   Priya    NaN

In [15]:
# Right
pd.merge(students, marks, on="ID", how="right")

   ID    Name  Marks
0   1  Akshat     95
1   2   Rahul     88
2   4     NaN     75

In [16]:
# outer
pd.merge(students, marks, on="ID", how="outer")

   ID    Name  Marks
0   1  Akshat   95.0
1   2   Rahul   88.0
2   3   Priya    NaN
3   4     NaN   75.0

In [19]:
# . Merge on Different Column Names
df1 = pd.DataFrame({
    "Student_ID":[1,2],
    "Name":["Akshat","Rahul"]
})

df2 = pd.DataFrame({
    "ID":[1,2],
    "Marks":[90,80]
})

pd.merge(df1, df2,
         left_on="Student_ID",
         right_on="ID")

   Student_ID    Name  ID  Marks
0           1  Akshat   1     90
1           2   Rahul   2     80

In [20]:
# Join (join())

# Works using index.

df1 = pd.DataFrame({
    "Name":["Akshat","Rahul"]
}, index=[1,2])

df2 = pd.DataFrame({
    "Marks":[95,88]
}, index=[1,2])

df1.join(df2)

     Name  Marks
1  Akshat     95
2   Rahul     88

In [22]:
# Missing Data

# # Missing values are represented by
df = pd.DataFrame({
    "Name":["Akshat","Rahul",None],
    "Age":[21,None,20]
})

In [23]:
# Detect Missing Values
# isnull()
df.isnull()

    Name    Age
0  False  False
1  False   True
2   True  False

In [24]:
# notnull()
df.notnull()

    Name    Age
0   True   True
1   True  False
2  False   True

In [25]:
# Fill Missing Values
# Fill with Zero
df.fillna(0)

     Name   Age
0  Akshat  21.0
1   Rahul   0.0
2       0  20.0

In [31]:
# Fill with String
df.fillna("Unknown")

      Name   Age
0   Akshat  21.0
1    Rahul  18.0
2  Unknown  20.0

In [28]:
# Fill Particular Column
df["Age"] = df["Age"].fillna(18)

In [32]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [10, None, None, 40]
})

print(df)

   Marks
0   10.0
1    NaN
2    NaN
3   40.0

In [33]:
df.bfill()

   Marks
0   10.0
1   40.0
2   40.0
3   40.0

In [35]:
# Forward Fill
df.ffill()

# Backward Fill
df.bfill()

   Marks
0   10.0
1   40.0
2   40.0
3   40.0

In [37]:
df.dropna()

   Marks
0   10.0
3   40.0

In [38]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [39]:
df.dropna(how="all")

   Marks
0   10.0
3   40.0

In [40]:
df.replace("Unknown","Akshat")

   Marks
0   10.0
1    NaN
2    NaN
3   40.0

In [41]:
df.drop_duplicates()

   Marks
0   10.0
1    NaN
3   40.0

In [43]:
df.drop(0)

   Marks
1    NaN
2    NaN
3   40.0

In [45]:
df.rename(columns={
    "Age":"Student Age"
})

   Marks
0   10.0
1    NaN
2    NaN
3   40.0

In [52]:
pd.merge(students, marks, on="ID", how="left")

   ID    Name  Marks
0   1  Akshat   95.0
1   2   Rahul   88.0
2   3   Priya    NaN