In [1]:
import pandas as pd

In [2]:
data = [10, 20, 30, 40]

s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

print(s)

a    10
b    20
c    30
dtype: int64

In [4]:
data = {'a': 10, 'b': 20, 'c': 30}

s = pd.Series(data)

print(s)

a    10
b    20
c    30
dtype: int64

In [5]:
s = pd.Series(5, index=['a', 'b', 'c'])

print(s)

a    5
b    5
c    5
dtype: int64

In [6]:
# Datafranes 
import pandas as pd
data = {
    "Name": ["Akshat", "Rahul", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Kota", "Delhi", "Jaipur"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age    City
0  Akshat   21    Kota
1   Rahul   22   Delhi
2   Priya   20  Jaipur

In [9]:
import pandas as pd

data = [
    ["Akshat", 21, "Kota"],
    ["Rahul", 22, "Delhi"],
    ["Priya", 20, "Jaipur"]
]

df = pd.DataFrame(data)

print(df)

        0   1       2
0  Akshat  21    Kota
1   Rahul  22   Delhi
2   Priya  20  Jaipur

In [10]:
import numpy as np

arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

df = pd.DataFrame(arr, columns=["A", "B"])

print(df)

   A  B
0  1  2
1  3  4
2  5  6

In [11]:
df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
data = {
    "Name": ["Akshat", "Rahul", "Priya"],
    "Marks": [90, 85, 95]
}

df = pd.DataFrame(data, index=["S1", "S2", "S3"])

print(df)

      Name  Marks
S1  Akshat     90
S2   Rahul     85
S3   Priya     95

In [13]:
import pandas as pd

data = {
    "Name": ["Akshat", "Rahul", "Priya", "Aman", "Neha"],
    "Age": [21, 22, 20, 23, 19],
    "Marks": [90, 75, 95, 65, 88],
    "City": ["Kota", "Delhi", "Jaipur", "Delhi", "Kota"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Marks    City
0  Akshat   21     90    Kota
1   Rahul   22     75   Delhi
2   Priya   20     95  Jaipur
3    Aman   23     65   Delhi
4    Neha   19     88    Kota

In [14]:
df[df["Age"] > 20]

     Name  Age  Marks   City
0  Akshat   21     90   Kota
1   Rahul   22     75  Delhi
3    Aman   23     65  Delhi

In [15]:
df[df["Marks"] >= 90]

     Name  Age  Marks    City
0  Akshat   21     90    Kota
2   Priya   20     95  Jaipur

In [16]:
df[(df["Age"] > 20) & (df["Marks"] > 80)]

     Name  Age  Marks  City
0  Akshat   21     90  Kota

In [17]:
df[(df["City"] == "Delhi") | (df["Marks"] > 90)]

    Name  Age  Marks    City
1  Rahul   22     75   Delhi
2  Priya   20     95  Jaipur
3   Aman   23     65   Delhi

In [18]:
df[~(df["City"] == "Delhi")]

     Name  Age  Marks    City
0  Akshat   21     90    Kota
2   Priya   20     95  Jaipur
4    Neha   19     88    Kota

In [19]:
df[df["Name"].str.startswith("A")]

     Name  Age  Marks   City
0  Akshat   21     90   Kota
3    Aman   23     65  Delhi

In [20]:
df[df["Marks"].isnull()]

Empty DataFrame
Columns: [Name, Age, Marks, City]
Index: []

In [21]:
df[(df["Age"] > 20) & (df["City"] == "Kota")]

     Name  Age  Marks  City
0  Akshat   21     90  Kota